--- 
- 
  connection: local
  gather_facts: false
  hosts: all
  name: "Create Report from Netbox Data"
  tasks: 
    - 
      blockinfile: 
        block: |
            netbox_data:
            {% for node in play_hosts %}
              - { node: {{ node }} , type: {{ hostvars[node].device_types[0] }} , mgmt_ip: {{ hostvars[node].ansible_host }} }
            {% endfor %}
        create: true
        path: ./netbox_report.yaml
      delegate_to: localhost
      name: "Build Report"
      run_once: true